/* TOPIK II (3·4급) 스타일 연습 문제 은행 */
window.TOPIK_BANK = [
  /* ===== 어휘 ===== */
  {
    id: "v01", section: "vocab", level: 3,
    stem: "다음 ( )에 들어갈 말로 가장 알맞은 것을 고르십시오.",
    passage: "시험이 끝난 후에 친구들과 함께 맛있는 음식을 ( ).",
    choices: ["먹기로 했다", "먹을까 한다", "먹는 중이다", "먹고 말았다"],
    answer: 0,
    explain: {
      ko: "이미 결정된 계획에는 ‘-기로 하다’가 자연스럽습니다.",
      vi: "Kế hoạch đã quyết định dùng ‘-기로 하다’.",
      en: "For a decided plan, ‘-기로 하다’ fits best.",
      zh: "已决定的计划用‘-기로 하다’最自然。",
      ja: "すでに決めた計画には「-기로 하다」が自然です。",
    },
  },
  {
    id: "v02", section: "vocab", level: 3,
    stem: "다음 밑줄 친 부분과 의미가 가장 비슷한 것을 고르십시오.",
    passage: "그 소식은 금방 온 동네에 <u>퍼졌다</u>.",
    choices: ["알려졌다", "사라졌다", "줄어들었다", "모였다"],
    answer: 0,
    explain: {
      ko: "‘퍼지다’는 소식·소문 등이 널리 알려지다는 뜻입니다.",
      vi: "‘퍼지다’ nghĩa là tin tức lan rộng / được biết đến.",
      en: "‘퍼지다’ means news spreads and becomes known.",
      zh: "‘퍼지다’表示消息广泛传开。",
      ja: "「퍼지다」は知らせが広く伝わるという意味です。",
    },
  },
  {
    id: "v03", section: "vocab", level: 4,
    stem: "다음 ( )에 들어갈 말로 가장 알맞은 것을 고르십시오.",
    passage: "그 문제는 생각보다 ( ) 해결되지 않았다.",
    choices: ["쉽게", "갑자기", "우연히", "드디어"],
    answer: 0,
    explain: {
      ko: "‘생각보다 ~지 않다’와 잘 어울리는 말은 ‘쉽게’입니다.",
      vi: "Với ‘생각보다 ~지 않다’, đáp án hợp nhất là ‘쉽게’.",
      en: "With ‘생각보다 ~지 않다’, ‘쉽게’ is the best fit.",
      zh: "与‘생각보다 ~지 않다’最搭配的是‘쉽게’。",
      ja: "「생각보다 ~지 않다」には「쉽게」が最も自然です。",
    },
  },
  {
    id: "v04", section: "vocab", level: 3,
    stem: "다음 중 밑줄 친 말의 쓰임이 다른 것을 고르십시오.",
    passage: "① 문을 <u>열다</u>　② 책을 <u>열다</u>　③ 회의를 <u>열다</u>　④ 창문을 <u>열다</u>",
    choices: ["①", "②", "③", "④"],
    answer: 2,
    explain: {
      ko: "③ ‘회의를 열다’는 ‘개최하다’의 뜻으로, 물리적 ‘열다’와 다릅니다.",
      vi: "③ ‘회의를 열다’ nghĩa là tổ chức họp, khác với ‘mở’ vật lý.",
      en: "③ means to hold a meeting, unlike physical ‘open’.",
      zh: "③是‘召开会议’，与物理上的‘打开’不同。",
      ja: "③は開催の意味で、物理的な「開く」と異なります。",
    },
  },
  {
    id: "v05", section: "vocab", level: 4,
    stem: "다음 ( )에 들어갈 말로 가장 알맞은 것을 고르십시오.",
    passage: "환경 보호를 위해 일회용품 사용을 ( ) 합니다.",
    choices: ["자제", "강조", "확대", "촉진"],
    answer: 0,
    explain: {
      ko: "사용을 줄여야 하므로 ‘자제하다’가 맞습니다.",
      vi: "Cần hạn chế sử dụng → ‘자제’.",
      en: "We should restrain use → ‘자제’.",
      zh: "应控制使用 → ‘자제’。",
      ja: "使用を控える →「자제」。",
    },
  },
  {
    id: "v06", section: "vocab", level: 3,
    stem: "다음 ( )에 공통으로 들어갈 동사를 고르십시오.",
    passage: "시간을 ( ) / 약속을 ( ) / 돈을 ( )",
    choices: ["지키다", "만들다", "보내다", "찾다"],
    answer: 0,
    explain: {
      ko: "‘시간을/약속을/돈을 지키다’는 모두 자연스러운 결합입니다.",
      vi: "‘지키다’ kết hợp tự nhiên với thời gian, lời hẹn, tiền.",
      en: "‘지키다’ collocates with time, appointments, and money.",
      zh: "‘지키다’可与时间、约定、金钱搭配。",
      ja: "「지키다」は時間・約束・お金と自然に結び付きます。",
    },
  },
  {
    id: "v07", section: "vocab", level: 4,
    stem: "다음 밑줄 친 부분과 바꿔 쓸 수 있는 것을 고르십시오.",
    passage: "그 제안은 <u>타당하다</u>고 생각한다.",
    choices: ["합리적이다", "위험하다", "복잡하다", "단순하다"],
    answer: 0,
    explain: {
      ko: "‘타당하다’는 ‘합리적이다’와 의미가 가깝습니다.",
      vi: "‘타당하다’ gần nghĩa ‘합리적이다’ (hợp lý).",
      en: "‘타당하다’ is close to ‘합리적이다’ (reasonable).",
      zh: "‘타당하다’与‘합리적이다’(合理)接近。",
      ja: "「타당하다」は「합리적이다」に近い意味です。",
    },
  },
  {
    id: "v08", section: "vocab", level: 3,
    stem: "다음 ( )에 들어갈 말로 가장 알맞은 것을 고르십시오.",
    passage: "비가 와서 소풍이 ( ) 취소되었다.",
    choices: ["부득이", "다행히", "일부러", "드디어"],
    answer: 0,
    explain: {
      ko: "어쩔 수 없이 취소된 상황이므로 ‘부득이’가 알맞습니다.",
      vi: "Bị hủy vì lý do bất khả kháng → ‘부득이’.",
      en: "Cancelled unavoidably → ‘부득이’.",
      zh: "不得已取消 → ‘부득이’。",
      ja: "やむを得ず中止 →「부득이」。",
    },
  },

  /* ===== 문법 ===== */
  {
    id: "g01", section: "grammar", level: 3,
    stem: "다음 ( )에 들어갈 말로 가장 알맞은 것을 고르십시오.",
    passage: "바쁘더라도 건강을 ( ) 운동을 해야 한다.",
    choices: ["위해", "통해", "대해", "의해"],
    answer: 0,
    explain: {
      ko: "목적·이익을 나타낼 때는 ‘위해’를 씁니다.",
      vi: "Chỉ mục đích/lợi ích dùng ‘위해’.",
      en: "Use ‘위해’ for purpose/benefit.",
      zh: "表示目的或利益用‘위해’。",
      ja: "目的・利益を表すときは「위해」を使います。",
    },
  },
  {
    id: "g02", section: "grammar", level: 3,
    stem: "다음 ( )에 들어갈 말로 가장 알맞은 것을 고르십시오.",
    passage: "날씨가 추워( ) 감기에 걸린 사람이 늘었다.",
    choices: ["지면서", "더라도", "거나", "든지"],
    answer: 0,
    explain: {
      ko: "변화가 일어나면서 다른 일도 함께 일어남을 ‘-면서’로 나타냅니다.",
      vi: "Hai việc xảy ra cùng lúc theo sự thay đổi → ‘-면서’.",
      en: "As one change happens, another occurs → ‘-면서’.",
      zh: "随着变化同时发生 → ‘-면서’。",
      ja: "変化とともに別のことが起こる →「-면서」。",
    },
  },
  {
    id: "g03", section: "grammar", level: 4,
    stem: "다음 ( )에 들어갈 말로 가장 알맞은 것을 고르십시오.",
    passage: "아무리 바빠도 식사는 ( ) 안 된다.",
    choices: ["거르면", "거를수록", "거른다고", "거를지라도"],
    answer: 0,
    explain: {
      ko: "금지·당위를 나타낼 때 ‘-으면 안 되다’를 씁니다.",
      vi: "Cấm đoán / không được phép → ‘-으면 안 되다’.",
      en: "Prohibition uses ‘-으면 안 되다’.",
      zh: "表示禁止用‘-으면 안 되다’。",
      ja: "禁止・当為は「-으면 안 되다」で表します。",
    },
  },
  {
    id: "g04", section: "grammar", level: 3,
    stem: "다음 ( )에 들어갈 말로 가장 알맞은 것을 고르십시오.",
    passage: "친구가 도와준 ( ) 일을 빨리 끝낼 수 있었다.",
    choices: ["덕분에", "탓에", "바람에", "통에"],
    answer: 0,
    explain: {
      ko: "좋은 결과에 대한 원인에는 ‘덕분에’를 씁니다.",
      vi: "Nguyên nhân dẫn đến kết quả tốt → ‘덕분에’.",
      en: "Positive cause uses ‘덕분에’.",
      zh: "导致好结果的原因用‘덕분에’。",
      ja: "良い結果の原因には「덕분에」を使います。",
    },
  },
  {
    id: "g05", section: "grammar", level: 4,
    stem: "다음 ( )에 들어갈 말로 가장 알맞은 것을 고르십시오.",
    passage: "그 책을 읽( ) 생각이 많이 바뀌었다.",
    choices: ["고 나서", "고 보니", "고자", "거나"],
    answer: 0,
    explain: {
      ko: "어떤 행동을 한 뒤에 생긴 변화를 ‘-고 나서’로 나타냅니다.",
      vi: "Sau khi làm xong việc gì đó → ‘-고 나서’.",
      en: "After finishing an action → ‘-고 나서’.",
      zh: "做完某事后 → ‘-고 나서’。",
      ja: "動作の後に起きた変化は「-고 나서」。",
    },
  },
  {
    id: "g06", section: "grammar", level: 3,
    stem: "다음 ( )에 들어갈 말로 가장 알맞은 것을 고르십시오.",
    passage: "비가 올 ( ) 우산을 가지고 가세요.",
    choices: ["테니까", "텐데", "테면", "테다가"],
    answer: 0,
    explain: {
      ko: "추측을 근거로 조언할 때 ‘-(으)ㄹ 테니까’를 씁니다.",
      vi: "Đưa lời khuyên dựa trên phỏng đoán → ‘-(으)ㄹ 테니까’.",
      en: "Advice based on assumption uses ‘-(으)ㄹ 테니까’.",
      zh: "基于推测提出建议用‘-(으)ㄹ 테니까’。",
      ja: "推測を根拠に助言するときは「-(으)ㄹ 테니까」。",
    },
  },
  {
    id: "g07", section: "grammar", level: 4,
    stem: "다음 ( )에 들어갈 말로 가장 알맞은 것을 고르십시오.",
    passage: "늦게 출발하는 ( ) 택시를 타기로 했다.",
    choices: ["바람에", "덕분에", "김에", "겸"],
    answer: 0,
    explain: {
      ko: "예상치 못한 이유로 부정적인 결과가 나올 때 ‘바람에’를 씁니다. 여기에서는 늦어서 택시를 탄 상황입니다.",
      vi: "Vì lý do ngoài ý muốn dẫn đến việc phải đi taxi → ‘바람에’.",
      en: "An unexpected reason leading to taking a taxi → ‘바람에’.",
      zh: "因意外原因而打车 → ‘바람에’。",
      ja: "予想外の理由でタクシーに乗った状況 →「바람에」。",
    },
  },
  {
    id: "g08", section: "grammar", level: 3,
    stem: "다음 ( )에 들어갈 말로 가장 알맞은 것을 고르십시오.",
    passage: "한국어를 열심히 공부한 ( ) 시험에 합격했다.",
    choices: ["결과", "대신", "만큼", "대로"],
    answer: 0,
    explain: {
      ko: "어떤 행위의 결말을 말할 때 ‘-(으)ㄴ 결과’를 씁니다.",
      vi: "Kết quả của hành động → ‘-(으)ㄴ 결과’.",
      en: "Outcome of an action → ‘-(으)ㄴ 결과’.",
      zh: "行为的结果 → ‘-(으)ㄴ 결과’。",
      ja: "行為の結末は「-(으)ㄴ 결과」で表します。",
    },
  },

  /* ===== 읽기 ===== */
  {
    id: "r01", section: "reading", level: 3,
    stem: "다음 글의 내용과 같은 것을 고르십시오.",
    passage: "요즘 많은 사람들이 아침 일찍 운동을 한다. 아침 운동은 하루를 활기차게 시작할 수 있게 해 준다. 또한 규칙적인 운동은 스트레스를 줄이는 데도 도움이 된다.",
    choices: [
      "아침 운동은 하루를 활기차게 시작하게 한다",
      "사람들은 저녁에만 운동을 한다",
      "운동은 스트레스를 늘린다",
      "아침 운동은 도움이 되지 않는다",
    ],
    answer: 0,
    explain: {
      ko: "글에서 아침 운동이 하루를 활기차게 시작하게 한다고 했습니다.",
      vi: "Bài đọc nói tập sáng giúp bắt đầu ngày tràn đầy năng lượng.",
      en: "The text says morning exercise helps start the day energetically.",
      zh: "文章写到晨练能让人充满活力地开始一天。",
      ja: "本文は朝の運動で一日を元気に始められると述べています。",
    },
  },
  {
    id: "r02", section: "reading", level: 3,
    stem: "다음 글에서 <보기>의 단어가 들어갈 곳으로 가장 알맞은 것을 고르십시오.",
    passage: "<보기> 따라서<br><br>재활용은 자원을 아끼는 좋은 방법이다. ( ① ) 환경을 보호하는 데도 큰 도움이 된다. ( ② ) 요즘 많은 나라에서 재활용을 장려하고 있다. ( ③ ) 개인의 작은 실천이 모여 큰 변화를 만든다. ( ④ )",
    choices: ["①", "②", "③", "④"],
    answer: 1,
    explain: {
      ko: "앞 문장의 결과에 해당하는 내용 앞에 ‘따라서’가 자연스럽습니다 → ②.",
      vi: "‘따라서’ (do đó) đặt trước câu kết luận → vị trí ②.",
      en: "‘따라서’ (therefore) fits before the concluding result → ②.",
      zh: "‘따라서’(因此)放在结论句前最自然 → ②。",
      ja: "「따라서」(したがって)は結論の前 → ②。",
    },
  },
  {
    id: "r03", section: "reading", level: 4,
    stem: "다음 글의 중심으로 가장 알맞은 것을 고르십시오.",
    passage: "스마트폰은 생활에 편리함을 주지만 과도한 사용은 수면 부족과 집중력 저하를 가져올 수 있다. 따라서 사용 시간을 스스로 정하고 지키는 습관이 필요하다.",
    choices: [
      "스마트폰 사용 시간을 조절해야 한다",
      "스마트폰은 전혀 쓸모가 없다",
      "수면은 중요하지 않다",
      "집중력은 타고나는 것이다",
    ],
    answer: 0,
    explain: {
      ko: "글의 핵심은 편리함과 부작용을 말한 뒤 사용 시간 조절을 강조한 것입니다.",
      vi: "Ý chính: cần tự kiểm soát thời gian dùng điện thoại.",
      en: "Main idea: we should control smartphone usage time.",
      zh: "中心思想：应控制使用手机的时间。",
      ja: "中心はスマホの使用時間を調節すべきだという点です。",
    },
  },
  {
    id: "r04", section: "reading", level: 4,
    stem: "다음 글의 내용과 다른 것을 고르십시오.",
    passage: "도서관은 책을 빌릴 수 있을 뿐 아니라 공부할 공간을 제공한다. 최근에는 온라인으로도 자료를 검색할 수 있게 되었다. 하지만 모든 자료가 무료인 것은 아니다.",
    choices: [
      "도서관의 모든 자료는 무료이다",
      "도서관에서 책을 빌릴 수 있다",
      "공부할 공간이 있다",
      "온라인 검색이 가능하다",
    ],
    answer: 0,
    explain: {
      ko: "글은 ‘모든 자료가 무료인 것은 아니다’라고 했으므로 ①이 내용과 다릅니다.",
      vi: "Bài nói không phải mọi tài liệu đều miễn phí → ① sai nội dung.",
      en: "The text says not all materials are free → ① is false.",
      zh: "文中说并非所有资料都免费 → ①与内容不符。",
      ja: "全文は「すべて無料ではない」とあるため①が不一致です。",
    },
  },
  {
    id: "r05", section: "reading", level: 3,
    stem: "다음을 읽고 물음에 답하십시오. 필자가 제안하는 것은 무엇입니까?",
    passage: "음식물 쓰레기를 줄이려면 장을 보기 전에 필요한 재료를 미리 적어 두는 것이 좋다. 또한 남은 음식은 다음날 다른 요리로 활용할 수 있다.",
    choices: [
      "필요한 재료를 미리 메모하고 남은 음식을 활용하라",
      "장을 자주 보라",
      "음식을 더 많이 만들어라",
      "쓰레기를 그냥 버려라",
    ],
    answer: 0,
    explain: {
      ko: "필자는 미리 메모하기와 남은 음식 활용을 제안합니다.",
      vi: "Tác giả đề xuất ghi chú trước và tái sử dụng đồ ăn thừa.",
      en: "The writer suggests listing ingredients and reusing leftovers.",
      zh: "作者建议事先记下所需食材并活用剩菜。",
      ja: "筆者はメモと余り物の活用を提案しています。",
    },
  },
  {
    id: "r06", section: "reading", level: 4,
    stem: "다음 글에서 밑줄 친 부분이 가리키는 것을 고르십시오.",
    passage: "많은 기업이 유연 근무제를 도입하고 있다. <u>이것</u>은 직원들의 만족도를 높이고 업무 효율도 개선하는 효과가 있다.",
    choices: ["유연 근무제", "많은 기업", "직원들", "업무 효율"],
    answer: 0,
    explain: {
      ko: "‘이것’은 바로 앞 내용인 ‘유연 근무제’를 가리킵니다.",
      vi: "‘이것’ chỉ ‘유연 근무제’ (chế độ làm việc linh hoạt) ở câu trước.",
      en: "‘이것’ refers to ‘flexible work’ mentioned just before.",
      zh: "‘이것’指前面的‘弹性工作制’。",
      ja: "「이것」は直前の「柔軟勤務制」を指します。",
    },
  },
  {
    id: "r07", section: "reading", level: 3,
    stem: "다음 안내문의 내용과 같은 것을 고르십시오.",
    passage: "[문화 센터 수강 안내]<br>· 신청 기간: 3월 1일~3월 10일<br>· 수강료: 5만 원 (교재비 별도)<br>· 문의: 02-123-4567",
    choices: [
      "교재비는 수강료에 포함되어 있지 않다",
      "신청은 3월 이후에도 가능하다",
      "수강료는 무료이다",
      "문의 전화가 없다",
    ],
    answer: 0,
    explain: {
      ko: "‘교재비 별도’이므로 수강료에 포함되지 않습니다.",
      vi: "Ghi ‘교재비 별도’ → tiền giáo trình không gồm trong học phí.",
      en: "‘Textbook fee separate’ means it is not included.",
      zh: "写明教材费另计，故不包含在学费中。",
      ja: "「教材費別途」なので受講料に含まれません。",
    },
  },
  {
    id: "r08", section: "reading", level: 4,
    stem: "다음 글의 빈칸에 들어갈 말로 가장 알맞은 것을 고르십시오.",
    passage: "도시는 일자리가 많고 생활이 편리하다. (　　　) 집값이 비싸고 공기가 나쁜 단점도 있다.",
    choices: ["반면에", "게다가", "드디어", "반드시"],
    answer: 0,
    explain: {
      ko: "장점 뒤에 대비되는 단점이 나오므로 ‘반면에’이 알맞습니다.",
      vi: "Đối lập ưu/nhược điểm → ‘반면에’.",
      en: "Contrast between pros and cons → ‘반면에’.",
      zh: "优缺点对比 → ‘반면에’。",
      ja: "長所と短所の対比 →「반면에」。",
    },
  },

  /* ===== 듣기 ===== */
  {
    id: "l01", section: "listening", level: 3,
    stem: "잘 듣고 이어서 할 말로 가장 알맞은 것을 고르십시오.",
    audioText: "가: 내일 회의가 몇 시에 시작하죠? 나: 오전 열 시입니다. 가: 알겠습니다. 그럼 아홉 시반까지 갈게요.",
    choices: [
      "네, 그렇게 해 주세요.",
      "회의가 취소됐어요.",
      "오늘 날씨가 좋아요.",
      "점심을 먹읍시다.",
    ],
    answer: 0,
    explain: {
      ko: "상대가 도착 시간을 말했으므로 ‘그렇게 해 주세요’가 자연스러운 응답입니다.",
      vi: "Đối phương nói sẽ đến lúc 9:30 → đáp lại xác nhận là hợp lý.",
      en: "The other person states an arrival time, so a confirming reply fits.",
      zh: "对方说明到达时间，确认应答最自然。",
      ja: "到着時間を伝えた相手への確認の返事が自然です。",
    },
  },
  {
    id: "l02", section: "listening", level: 3,
    stem: "잘 듣고 남자의 중심으로 가장 알맞은 것을 고르십시오.",
    audioText: "남자: 요즘 버스보다 지하철을 자주 이용해요. 길이 막히지 않아서 약속 시간에 늦을 일이 없거든요.",
    choices: [
      "지하철이 약속 시간에 맞춰 가기에 좋다",
      "버스가 더 빠르다",
      "남자는 버스를 더 좋아한다",
      "길이 전혀 안 막힌다",
    ],
    answer: 0,
    explain: {
      ko: "남자는 지하철이 막히지 않아 시간에 맞추기 좋다고 말합니다.",
      vi: "Nam nói tàu điện ngầm giúp đúng giờ vì ít kẹt xe.",
      en: "He says the subway helps him arrive on time.",
      zh: "男士说地铁不堵、便于守时。",
      ja: "男性は地下鉄の方が時間に間に合いやすいと言っています。",
    },
  },
  {
    id: "l03", section: "listening", level: 4,
    stem: "잘 듣고 들은 내용과 같은 것을 고르십시오.",
    audioText: "여자: 이번 주말에 전시회에 가려고요. 표는 인터넷으로 미리 예매해야 해요. 현장에서는 표가 없을 수도 있대요.",
    choices: [
      "표를 미리 예매하는 것이 좋다",
      "현장 구매가 더 쉽다",
      "전시회는 평일에만 한다",
      "인터넷 예매가 불가능하다",
    ],
    answer: 0,
    explain: {
      ko: "여자는 인터넷 사전 예매를 권하는 내용입니다.",
      vi: "Nữ khuyên nên đặt vé trước trên mạng.",
      en: "She recommends booking tickets online in advance.",
      zh: "女士建议网上提前订票。",
      ja: "女性はネットでの事前予約を勧めています。",
    },
  },
  {
    id: "l04", section: "listening", level: 3,
    stem: "잘 듣고 대화 내용과 일치하는 것을 고르십시오.",
    audioText: "가: 이 식당 예약하셨어요? 나: 네, 저녁 일곱 시로 예약했어요. 가: 인원이 몇 명이죠? 나: 네 명이요.",
    choices: [
      "저녁 일곱 시에 네 명이 예약했다",
      "점심 예약을 했다",
      "두 명이 간다",
      "예약을 하지 않았다",
    ],
    answer: 0,
    explain: {
      ko: "저녁 7시, 4명 예약이라고 명확히 말했습니다.",
      vi: "Đặt bàn 7 giờ tối, 4 người.",
      en: "Reservation is for 7 p.m. for four people.",
      zh: "预约是晚上7点、四人。",
      ja: "夜7時、4名の予約です。",
    },
  },
  {
    id: "l05", section: "listening", level: 4,
    stem: "잘 듣고 여자의 태도로 가장 알맞은 것을 고르십시오.",
    audioText: "남자: 보고서를 내일까지 끝내야 하는데 시간이 부족해요. 여자: 제가 자료 정리하는 것을 도와드릴까요? 함께하면 더 빨리 끝낼 수 있을 거예요.",
    choices: [
      "도움을 제안하고 있다",
      "불만을 표시하고 있다",
      "거절하고 있다",
      "사과하고 있다",
    ],
    answer: 0,
    explain: {
      ko: "여자는 자료 정리를 도와주겠다고 제안합니다.",
      vi: "Nữ đề nghị giúp sắp xếp tài liệu.",
      en: "The woman offers to help organize materials.",
      zh: "女士提出帮忙整理资料。",
      ja: "女性は資料整理の手伝いを提案しています。",
    },
  },
  {
    id: "l06", section: "listening", level: 3,
    stem: "잘 듣고 무엇에 대한 이야기인지 고르십시오.",
    audioText: "안내 말씀 드립니다. 도서관은 저녁 아홉 시에 문을 닫습니다. 대출은 닫기 삼십 분 전까지 해 주시기 바랍니다.",
    choices: [
      "도서관 이용 시간 안내",
      "식당 메뉴 소개",
      "버스 시간표",
      "날씨 예보",
    ],
    answer: 0,
    explain: {
      ko: "도서관 폐관 시간과 대출 마감 안내입니다.",
      vi: "Thông báo giờ đóng cửa và hạn mượn sách thư viện.",
      en: "It is a library closing and lending notice.",
      zh: "这是图书馆闭馆与借书截止通知。",
      ja: "図書館の閉館・貸出締切の案内です。",
    },
  },
  {
    id: "l07", section: "listening", level: 4,
    stem: "잘 듣고 남자의 생각으로 가장 알맞은 것을 고르십시오.",
    audioText: "남자: 외국어를 배울 때는 매일 조금씩이라도 꾸준히 하는 게 중요해요. 하루 만에 많이 공부하는 것보다 효과가 더 크다고 생각해요.",
    choices: [
      "꾸준한 학습이 중요하다",
      "하루에 몰아서 공부해야 한다",
      "외국어 공부는 필요 없다",
      "가끔씩만 공부하면 된다",
    ],
    answer: 0,
    explain: {
      ko: "남자는 매일 조금씩 꾸준히 하는 것이 중요하다고 말합니다.",
      vi: "Nam cho rằng học đều đặn mỗi ngày quan trọng hơn học dồn.",
      en: "He believes steady daily study matters more than cramming.",
      zh: "男士认为每天坚持学习更重要。",
      ja: "男性は毎日の継続学習が大切だと考えています。",
    },
  },
  {
    id: "l08", section: "listening", level: 3,
    stem: "잘 듣고 여자가 할 일로 알맞은 것을 고르십시오.",
    audioText: "남자: 발표 자료 인쇄는 하셨어요? 여자: 아직이요. 지금 바로 프린터기로 가서 출력할게요.",
    choices: [
      "자료를 인쇄하러 간다",
      "발표를 취소한다",
      "회의를 시작한다",
      "집에 돌아간다",
    ],
    answer: 0,
    explain: {
      ko: "여자는 지금 바로 인쇄하러 간다고 했습니다.",
      vi: "Nữ nói sẽ đi in tài liệu ngay.",
      en: "She says she will go print the materials now.",
      zh: "女士说现在就去打印资料。",
      ja: "女性は今すぐ印刷しに行くと言っています。",
    },
  },
];
